global:
  clusterDomain: "insert-your-cluster-domain-here"
  huggingfacehubApiToken: "insert-your-huggingface-token-here"

codegen:
  image:
    repository: "insert-your-image-here"
    tag: "latest"
    gitRef: main
