global:
  clusterDomain: "insert-your-cluster-domain-here"

image:
  repository: "insert-your-image-here"
  tag: "latest"
  pullPolicy: IfNotPresent

source:
  contextDir: CodeGen
  gitRef: main
  gitUri: "https://github.com/opea-project/GenAIExamples.git"
  type: Git

strategy:
  type: Docker
  dockerfilePath: Dockerfile

replicaCount: 1

port: 7778

service:
  type: ClusterIP
  port: 7778
