kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: codegen-megaservice-server
  namespace: {{ .Release.Namespace }}
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "codegen:latest"
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  resources: {}
  runPolicy: SerialLatestOnly
  source:
    contextDir: CodeGen/docker
    git:
      ref: {{ .Values.codegen.image.gitRef }}
      uri: https://github.com/opea-project/GenAIExamples.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ConfigChange
