apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: codegen
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: codegen
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: codegen-0.1.0
  name: codegen
spec:
  port:
    targetPort: codegen
  to:
    kind: Service
    name: codegen
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: codegen
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: codegen
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: codegen-0.1.0
  name: codegen-tls
spec:
  host: codegen-react-ui-{{ .Release.Namespace }}.apps.{{ .Values.global.clusterDomain }}
  path: /v1/codegen
  port:
    targetPort: codegen
  tls:
    termination: edge
  to:
    kind: Service
    name: codegen
    weight: 100
  wildcardPolicy: None
