kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ include "llm-uservice.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "llm-tgi:latest"
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  resources: {}
  runPolicy: SerialLatestOnly
  source:
    git:
      ref: {{ .Values.llmUservice.image.gitRef }}
      uri: {{ .Values.llmUservice.image.gitUri }}
    type: {{ .Values.llmUservice.image.type }}
  strategy:
    type: {{ .Values.llmUservice.image.strategy.type }}
    dockerStrategy:
      dockerfilePath: {{ .Values.llmUservice.image.strategy.dockerfilePath }}
  triggers:
  - type: ConfigChange
