model:
  id: meta-llama/CodeLlama-7b-hf
  size: 50Gi

replicaCount: 1

port: 8080

image:
  repository: ghcr.io/huggingface/tgi-gaudi
  tag: 2.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

resources:
  limits:
    habana.ai/gaudi: 1
  requests:
    habana.ai/gaudi: 1

args:
- "--max-input-length"
- "1024"
- "--max-total-tokens"
- "2048"
