model:
  id: ise-uiuc/Magicoder-S-DS-6.7B
  size: 50Gi

replicaCount: 1

port: 8080

image:
  repository: ghcr.io/huggingface/text-generation-inference
  tag: 2.1.0
  pullPolicy: IfNotPresent
  
service:
  type: ClusterIP

resources: {}

args: []
