apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tgi.fullname" . }}
  labels:
    {{- include "tgi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tgi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tgi.selectorLabels" . | nindent 8 }}
    spec:
      securityContext: {}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: MODEL_ID
              value: "{{ .Values.model.id }}"
            - name: PORT
              value: {{ .Values.port | quote }}
            - name: NUMBA_CACHE_DIR
              value: /data
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  key: HUGGING_FACE_HUB_TOKEN
                  name: hf-token
          securityContext: {}
          image: "ghcr.io/huggingface/tgi-gaudi:2.0.1"
          args:
          - "--max-input-length"
          - "1024"
          - "--max-total-tokens"
          - "2048"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /data
              name: model-volume
            - mountPath: /var/log/habana_logs
              name: logs-volume
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
            limits:
              habana.ai/gaudi: 1
            requests:
              habana.ai/gaudi: 1
      volumes:
      - emptyDir:
          sizeLimit: {{ .Values.model.size }}
        name: model-volume
      - emptyDir:
        name: logs-volume
