---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: react-ui
spec:
  lookupPolicy:
    local: true
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: react-ui
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "react-ui:{{ .Values.reactUi.image.tag }}"
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  resources: {}
  runPolicy: SerialLatestOnly
  source:
    contextDir: CodeGen/ui
    git:
      ref: {{ .Values.reactUi.image.gitRef }}
      uri: https://github.com/opea-project/GenAIExamples.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      env:
      - name: VITE_CODE_GEN_URL
        value: https://codegen-react-ui-{{ .Release.Namespace }}.apps.{{ .Values.global.clusterDomain }}/v1/codegen
      dockerfilePath: docker/Dockerfile.react
  triggers:
  - type: ConfigChange
